### ISSUE TITLE
Please archive this repository

### ISSUE THREAD

**Issue by UweKrause** [lizhuohua/rust-mir-checker#15]
Dear author,

As you can see in the issues, people actually try to check this out.
Problem is, that this does not compile anymore.
To stop wasting peoples time, please either fix the description on how to compile this or please set the repository to "archived".

Thanks.

Wasted hours here: 2.
@everyone: Feel free to add more wasted hours below.

**Comment by lizhuohua** [comment]
Thank you for your interest in my project. I have finally found some time to revisit it recently. 

Due to upgrades of LLVM and the [breaking change](https://github.com/antoinemine/apron/issues/56) in GNU Make, it no longer compiled. However, these issues should now be resolved, and at least it compiles successfully on [GitHub Actions](https://github.com/lizhuohua/rust-mir-checker/actions/runs/9220202605/job/25366727033).
